version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.19.3"
replacements:
  name: "WaveyCapes"
  id: "waveycapes"
  version: "1.4.0"
  relocationpackage: "dev.tr7zw.waveycapes"
  modrinthid: kYuIpRLv
  curseforgeid: 521594
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - modrinth
  - curseforge
rootProject:
  template: "."
subProjects:
  WCFabric:
    template: "Fabric"
    replacements:
      dependencies: '
      modCompileOnly "curse.maven:morebanners-515000:3820969"
      
      modCompileOnly "curse.maven:minecraftcapes-mod-359836:4562672"
      '
  WCForge:
    template: "Forge"
    replacements:
      dependencies: '
      modImplementation "curse.maven:minecraftcapes-mod-359836:4562670"
      '