version: '0.0.1'
source: "https://github.com/tr7zw/ForgeFabricComposeTemplate/tree/1.19.3-mcpublish/"
replacements:
  group: "dev.tr7zw"
  name: "WaveyCapes"
  id: "waveycapes"
  version: "1.2.2"
  author: "tr7zw"
  relocationpackage: "dev.tr7zw.waveycapes"
  dependencies: '
  '
  licensename: "LICENSE"
  modrinthid: kYuIpRLv
  curseforgeid: 521594
rootProject:
  template: "."
subProjects:
  WCFabric:
    template: "Fabric"
    replacements:
      dependencies: '
      modCompileOnly "curse.maven:morebanners-515000:3820969"
      
      modCompileOnly "curse.maven:minecraftcapes-mod-359836:4019976"
      '
  WCForge:
    template: "Forge"
    replacements:
      dependencies: '
      modImplementation "curse.maven:minecraftcapes-mod-359836:4019977"
      '