modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/tr7zw/NotEnoughAnimations/issues"

license="tr7zw Protective License"
[[mods]]
modId="waveycapes"
version="1.3.1"
displayName="WaveyCapes Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/waveycapes"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="assets/waveycapes/icon.png"
authors="tr7zw"
description='''
The cape shouldn't be a static slab
'''
[[dependencies.waveycapes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"