name: Create Release
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Tag Name'
        required: true
      target:
        description: 'What to release'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - fabric
        - forge
      changelog:
        description: 'Changelog'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: make gradle wrapper executable
        run: chmod +x ./gradlecw
      - name: build
        run: ./gradlecw build
  GithubRelease:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Save Changelog
        run: echo "$LOG" > CHANGELOG.txt
        env:
          LOG: ${{ inputs.changelog }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.name }}
          tag_name: ${{ inputs.name }}
          body_path: CHANGELOG.txt
          generate_release_notes: true
          files: |
            WCFabric/build/libs/*
            WCForge/build/libs/*
            WCVersionless/build/libs/*
  ForgeRelease:
    needs: GithubRelease
    if: inputs.target == 'forge' || inputs.target == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Publish-Forge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 521594
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}  
          loaders: forge
          name: ${{inputs.name}} - Forge
          github-tag: ${{inputs.name}}
          version-type: beta
          files: '*Forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
      - name: Publish-Forge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: kYuIpRLv
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          name: ${{inputs.name}} - Forge
          github-tag: ${{inputs.name}}
          files: '*Forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
  FabricRelease:
    needs: GithubRelease
    if: inputs.target == 'fabric' || inputs.target == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Publish-Fabric
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: kYuIpRLv
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 521594
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}  
          loaders: fabric
          name: ${{inputs.name}} - Fabric
          github-tag: ${{inputs.name}}
          files: '*Fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
